# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm run clean:public
    npm install
    npm run build:prod
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ui/$(Build.BuildId).zip'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectedServiceName: 'licorneWebsite - Service Endpoint'
    WebAppKind: 'webAppLinux'
    WebAppName: 'licorneWebsite'
    RuntimeStack: 'NODE|10.14'
    StartupCommand: 'run start'